### ISSUE TITLE
削除人気高まるゲーミングPC　ゲーム動画でユーザー拡大

### ISSUE THREAD

**Issue by TKGJ** [TKGJ/polife#1]
###オンラインゲームや凝ったグラフィックのゲームを楽しむための高性能パソコン「ゲーミングPC」の人気が高まっている。調査会社GfKジャパンによると、2017年の個人向けパソコンの国内販売は、全体では前年比98％だったが、ゲーミングPCに限ると135％、金額では143％と好調。販売店には小中学生も訪れるという（記事「高くても売れる『ゲーミングPC』　小中学生にも人気」参照）。家庭用ゲーム機やスマートフォン（スマホ）が強く、パソコンでゲームを楽しむ人は少ないといわれてきた日本で、20万円を超えるモデルも珍しくないゲーミングPCがなぜ売れるのか。実際にゲーミングPCを販売するメーカーをたずね、人気の理由を探る。今回は「ALIENWARE」（エイリアンウエア）というブランドを持ち、積極的にゲーミングPCに取り組んできたデルの柳沢真吾氏に話を聞いた。(NIKKEI STYLE)asd

**Comment by TKGJ** [comment]
ゲーミングPCをげーパソへ

**Comment by Tlanway** [comment]
ゲーパソね
、
